### ISSUE TITLE
No release version of `action-cpplint`

### ISSUE THREAD

**Issue by LKreutzer** [reviewdog/action-cpplint#29]
Even though this action is used by a [number of repositories](https://sourcegraph.com/search?q=context:global+reviewdog/action-cpplint&patternType=standard&sm=0&groupBy=repo) there is currently no release of the `action-cpplint` action.

- Is there a plan to create a release? 
- Are there specific reasons why there is currently no release?

**Comment by shogo82148** [comment]
I've just released https://github.com/reviewdog/action-cpplint/releases/tag/v1.0.0
Have fun!
